CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);
CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId INTEGER REFERENCES projects(id)
);
-- INSERT PROJECT DATA
INSERT INTO projects(name, priority, description, deliverydate)
VALUES('Make a Web App', 1, 'Usando Js', '2020-06-23');
INSERT INTO projects(name, priority, description, deliverydate)
VALUES (
        'Make a Web App',
        1,
        'Usando React',
        '2020-06-24'
    );
INSERT INTO projects(name, priority, description, deliverydate)
VALUES ('Make a Web App', 1, 'Usando Vue', '2020-06-25');
-- INSERT TASK DATA
INSERT INTO tasks(name, done, projectID)
VALUES('Download recurses', false, 1);
INSERT INTO tasks(name, done, projectID)
VALUES('Create UI web', false, 1);
INSERT INTO tasks(name, done, projectID)
VALUES('Download react', false, 2);
INSERT INTO tasks(name, done, projectID)
VALUES('Design UI', false, 2);